x-service: &service
    image: thenewboston-backend:current
    restart: unless-stopped
    depends_on:
      redis:
        # TODO(dmu) LOW: Add redis health check and change to `condition: service_healthy`
        condition: service_started
    env_file:
      - path: '/etc/thenewboston/.env'
        required: false
    environment:
      THENEWBOSTON_SETTING_CHANNEL_LAYERS: '{"default":{"CONFIG":{"hosts":[["redis", 6379]]}}}'

services:

  redis:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    ports:
      # TODO(dmu) LOW: Do we need to expose to expose Redis to localhost in production?
      - 127.0.0.1:6379:6379
    volumes:
      - redis-data:/var/lib/redis

  app:
    <<: *service
    command: ./run-django.sh
    ports:
      - 127.0.0.1:8000:8000

  discord-bot:
    <<: *service
    command: ./run-discord-bot.sh

volumes:
  redis-data:
    driver: local
