[tool.poetry]
name = "thenewboston-backend"
version = "0.1.0"
description = ""
authors = ["bucky <buckyroberts@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "thenewboston"}]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.2"
djangorestframework = "^3.14.0"
psycopg2 = "^2.9.6"
django-filter = "^23.2"
django-split-settings = "^1.2.0"
pyyaml = "^6.0"
djangorestframework-simplejwt = "^5.2.2"
django-cors-headers = "^4.1.0"
pillow = "^9.5.0"
django-storages = "^1.13.2"
boto3 = "^1.26.155"
pynacl = "^1.5.0"
pydantic = "^1.10.9"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"
colorlog = "^6.7.0"

[tool.isort]
line_length = 119
multi_line_output = 5

[tool.yapf]
align_closing_bracket_with_visual_indent = true
based_on_style = "google"
coalesce_brackets = true
column_limit = 119
dedent_closing_brackets = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
