# Generated by Django 4.2.3 on 2024-03-26 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_various_changes'),
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='issue',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='github.issue'
            ),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='pull',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contributions',
                to='github.pull',
            ),
        ),
    ]
