# Generated by Django 4.2.3 on 2024-05-15 14:58

import django.utils.timezone as timezone
from django.db import migrations, models


def set_rewarded_at(apps, schema_editor):
    contribution_model = apps.get_model('contributions', 'Contribution')
    contribution_model.objects.filter(reward_amount__isnull=False).update(rewarded_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_repo_contribution_branch'),
        ('contributions', '0002_alter_contribution_issue_alter_contribution_pull'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contribution_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pull request'), (2, 'Manual')], default=1),
        ),
        migrations.AddField(
            model_name='contribution',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='github_user',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.CASCADE, to='github.githubuser'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='reward_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to='github.repo'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='assessment_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='assessment_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='rewarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_rewarded_at, reverse_code=migrations.RunPython.noop),
    ]
