# Generated by Django 5.2.1 on 2025-11-17 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('currencies', '0008_whitepaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonsai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('genus', models.CharField(blank=True, default='', max_length=255)),
                ('cultivar', models.CharField(blank=True, default='', max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('size', models.TextField()),
                ('origin', models.TextField()),
                ('pot', models.TextField()),
                ('teaser', models.CharField(max_length=500)),
                ('description', models.TextField()),
                (
                    'price_amount',
                    models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('draft', 'Draft'), ('published', 'Published')],
                        db_index=True,
                        default='draft',
                        max_length=20,
                    ),
                ),
                (
                    'price_currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='bonsais', to='currencies.currency'
                    ),
                ),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BonsaiHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                (
                    'bonsai',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='bonsais.bonsai'
                    ),
                ),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BonsaiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                (
                    'bonsai',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bonsais.bonsai'
                    ),
                ),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
