# Generated by Django 5.2.1 on 2026-01-29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bonsais', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='BonsaiImage'),
        migrations.DeleteModel(name='BonsaiHighlight'),
        migrations.DeleteModel(name='Bonsai'),
    ]
