# Generated by Django 5.2.1 on 2025-11-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bonsais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonsaiimage',
            name='url',
        ),
        migrations.AddField(
            model_name='bonsaiimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='bonsai_images/'),
        ),
    ]
