# Generated by Django 5.2.1 on 2025-11-24 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import thenewboston.connect_five.constants


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('currencies', '0008_whitepaper'),
        ('users', '0005_useragreement'),
        ('wallets', '0003_alter_wallet_created_date_alter_wallet_modified_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectFiveChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('stake_amount', models.PositiveBigIntegerField()),
                ('max_spend_amount', models.PositiveBigIntegerField()),
                ('time_limit_seconds', models.PositiveIntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('accepted', 'Accepted'),
                            ('cancelled', 'Cancelled'),
                            ('expired', 'Expired'),
                            ('pending', 'Pending'),
                        ],
                        default='pending',
                        max_length=12,
                    ),
                ),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'challenger',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='connect_five_challenges_sent',
                        to='users.user',
                    ),
                ),
                (
                    'currency',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
                ),
                (
                    'opponent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='connect_five_challenges_received',
                        to='users.user',
                    ),
                ),
            ],
            options={'ordering': ['-created_date']},
        ),
        migrations.CreateModel(
            name='ConnectFiveEscrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('player_a_contrib', models.PositiveBigIntegerField(default=0)),
                ('player_b_contrib', models.PositiveBigIntegerField(default=0)),
                ('total', models.PositiveBigIntegerField(default=0)),
                (
                    'status',
                    models.CharField(
                        choices=[('locked', 'Locked'), ('settled', 'Settled')],
                        default='locked',
                        max_length=12,
                    ),
                ),
                (
                    'challenge',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='escrow',
                        to='connect_five.connectfivechallenge',
                    ),
                ),
                (
                    'currency',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
                ),
                (
                    'player_a',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='connect_five_escrows_as_player_a',
                        to='users.user',
                    ),
                ),
                (
                    'player_b',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='connect_five_escrows_as_player_b',
                        to='users.user',
                    ),
                ),
            ],
            options={'ordering': ['-created_date']},
        ),
        migrations.CreateModel(
            name='ConnectFiveIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='connect_five_idempotency_keys',
                        to='users.user',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ConnectFiveMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('cancelled', 'Cancelled'),
                            ('draw', 'Draw'),
                            ('finished_connect5', 'Finished (Connect 5)'),
                            ('finished_timeout', 'Finished (Timeout)'),
                        ],
                        default='active',
                        max_length=20,
                    ),
                ),
                ('turn_number', models.PositiveIntegerField(default=1)),
                ('turn_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clock_a_remaining_ms', models.PositiveBigIntegerField()),
                ('clock_b_remaining_ms', models.PositiveBigIntegerField()),
                ('prize_pool_total', models.PositiveBigIntegerField(default=0)),
                ('max_spend_amount', models.PositiveBigIntegerField()),
                ('time_limit_seconds', models.PositiveIntegerField()),
                ('board_state', models.JSONField(default=thenewboston.connect_five.constants.create_empty_board)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                (
                    'active_player',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='connect_five_matches_active',
                        to='users.user',
                    ),
                ),
                (
                    'challenge',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='match',
                        to='connect_five.connectfivechallenge',
                    ),
                ),
                (
                    'player_a',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='connect_five_matches_as_player_a',
                        to='users.user',
                    ),
                ),
                (
                    'player_b',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='connect_five_matches_as_player_b',
                        to='users.user',
                    ),
                ),
                (
                    'winner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='connect_five_matches_won',
                        to='users.user',
                    ),
                ),
            ],
            options={'ordering': ['-created_date']},
        ),
        migrations.CreateModel(
            name='ConnectFiveMatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('spent_total', models.PositiveBigIntegerField(default=0)),
                ('inventory_h2', models.PositiveIntegerField(default=0)),
                ('inventory_v2', models.PositiveIntegerField(default=0)),
                ('inventory_cross4', models.PositiveIntegerField(default=0)),
                ('inventory_bomb', models.PositiveIntegerField(default=0)),
                (
                    'match',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='players',
                        to='connect_five.connectfivematch',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='connect_five_match_players',
                        to='users.user',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ConnectFiveMatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('challenge_accepted', 'Challenge Accepted'),
                            ('challenge_cancelled', 'Challenge Cancelled'),
                            ('challenge_expired', 'Challenge Expired'),
                            ('move', 'Move'),
                            ('purchase', 'Purchase'),
                            ('settlement', 'Settlement'),
                            ('timeout', 'Timeout'),
                        ],
                        max_length=32,
                    ),
                ),
                ('payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                (
                    'actor',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'
                    ),
                ),
                (
                    'match',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='events',
                        to='connect_five.connectfivematch',
                    ),
                ),
            ],
            options={'ordering': ['created_date']},
        ),
        migrations.CreateModel(
            name='ConnectFiveLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveBigIntegerField()),
                (
                    'direction',
                    models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('challenge_refund', 'Challenge Refund'),
                            ('purchase', 'Purchase'),
                            ('stake_accept', 'Stake Accept'),
                            ('stake_lock', 'Stake Lock'),
                            ('win_payout', 'Win Payout'),
                            ('draw_refund', 'Draw Refund'),
                        ],
                        max_length=32,
                    ),
                ),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                (
                    'escrow',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ledger_entries',
                        to='connect_five.connectfiveescrow',
                    ),
                ),
                (
                    'wallet',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='connect_five_ledger_entries',
                        to='wallets.wallet',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='connectfivematchplayer',
            constraint=models.UniqueConstraint(fields=('match', 'user'), name='unique_match_user'),
        ),
        migrations.AddConstraint(
            model_name='connectfiveidempotencykey',
            constraint=models.UniqueConstraint(
                fields=('user', 'key', 'action'), name='unique_connect_five_idempotency_key'
            ),
        ),
        migrations.AddConstraint(
            model_name='connectfiveledgerentry',
            constraint=models.UniqueConstraint(
                fields=('escrow', 'action', 'idempotency_key', 'wallet'),
                name='unique_connect_five_ledger_idempotency',
            ),
        ),
    ]
