# Generated by Django 5.2.1 on 2026-01-12 03:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('connect_five', '0002_remove_connect_five_idempotency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectfivechallenge',
            options={
                'ordering': ['-created_date'],
                'verbose_name': 'Connect Five Challenge',
                'verbose_name_plural': 'Connect Five Challenges',
            },
        ),
        migrations.AlterModelOptions(
            name='connectfiveescrow',
            options={
                'ordering': ['-created_date'],
                'verbose_name': 'Connect Five Escrow',
                'verbose_name_plural': 'Connect Five Escrows',
            },
        ),
        migrations.AlterModelOptions(
            name='connectfiveledgerentry',
            options={'verbose_name': 'Connect Five Ledger Entry', 'verbose_name_plural': 'Connect Five Ledger Entries'},
        ),
        migrations.AlterModelOptions(
            name='connectfivematch',
            options={
                'ordering': ['-created_date'],
                'verbose_name': 'Connect Five Match',
                'verbose_name_plural': 'Connect Five Matches',
            },
        ),
        migrations.AlterModelOptions(
            name='connectfivematchevent',
            options={
                'ordering': ['created_date'],
                'verbose_name': 'Connect Five Match Event',
                'verbose_name_plural': 'Connect Five Match Events',
            },
        ),
        migrations.AlterModelOptions(
            name='connectfivematchplayer',
            options={'verbose_name': 'Connect Five Match Player', 'verbose_name_plural': 'Connect Five Match Players'},
        ),
    ]
