# Generated by Django 5.2.1 on 2026-01-12 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('connect_five', '0003_alter_connectfivechallenge_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectfivechallenge',
            options={
                'ordering': ['-created_date'],
                'verbose_name': 'Connect Five challenge',
                'verbose_name_plural': 'Connect Five challenges',
            },
        ),
        migrations.AlterModelOptions(
            name='connectfiveescrow',
            options={
                'ordering': ['-created_date'],
                'verbose_name': 'Connect Five escrow',
                'verbose_name_plural': 'Connect Five escrows',
            },
        ),
        migrations.AlterModelOptions(
            name='connectfiveledgerentry',
            options={'verbose_name': 'Connect Five ledger entry', 'verbose_name_plural': 'Connect Five ledger entries'},
        ),
        migrations.AlterModelOptions(
            name='connectfivematch',
            options={
                'ordering': ['-created_date'],
                'verbose_name': 'Connect Five match',
                'verbose_name_plural': 'Connect Five matches',
            },
        ),
        migrations.AlterModelOptions(
            name='connectfivematchevent',
            options={
                'ordering': ['created_date'],
                'verbose_name': 'Connect Five match event',
                'verbose_name_plural': 'Connect Five match events',
            },
        ),
        migrations.AlterModelOptions(
            name='connectfivematchplayer',
            options={'verbose_name': 'Connect Five match player', 'verbose_name_plural': 'Connect Five match players'},
        ),
    ]
