# Generated by Django 5.2.1 on 2026-01-12 03:40

import django.db.models.deletion
from django.db import migrations, models

import thenewboston.connect_five.constants


class Migration(migrations.Migration):
    dependencies = [
        ('connect_five', '0004_alter_connectfivechallenge_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectFiveStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('elo', models.PositiveIntegerField(default=thenewboston.connect_five.constants.ELO_STARTING_SCORE)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='connect_five_stats',
                        to='users.user',
                    ),
                ),
            ],
            options={'verbose_name': 'Connect Five stats', 'verbose_name_plural': 'Connect Five stats'},
        ),
        migrations.AddField(
            model_name='connectfivechallenge',
            name='rematch_for',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='rematch_challenges',
                to='connect_five.connectfivematch',
            ),
        ),
        migrations.AddField(
            model_name='connectfivematch',
            name='player_a_elo_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectfivematch',
            name='player_a_elo_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectfivematch',
            name='player_b_elo_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectfivematch',
            name='player_b_elo_before',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
