# Generated by Django 5.2.1 on 2026-01-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('connect_five', '0005_connect_five_elo_rematch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectfivechallenge',
            name='status',
            field=models.CharField(
                choices=[
                    ('accepted', 'Accepted'),
                    ('cancelled', 'Cancelled'),
                    ('declined', 'Declined'),
                    ('expired', 'Expired'),
                    ('pending', 'Pending'),
                ],
                default='pending',
                max_length=12,
            ),
        ),
    ]
