# Generated by Django 5.2.1 on 2026-01-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('connect_five', '0007_reset_connect_five_data_and_remove_cross4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectfivematch',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'Active'),
                    ('cancelled', 'Cancelled'),
                    ('draw', 'Draw'),
                    ('finished_connect5', 'Finished (Connect 5)'),
                    ('finished_resign', 'Finished (Resign)'),
                    ('finished_timeout', 'Finished (Timeout)'),
                ],
                default='active',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='connectfivematchevent',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('challenge_accepted', 'Challenge Accepted'),
                    ('challenge_cancelled', 'Challenge Cancelled'),
                    ('challenge_expired', 'Challenge Expired'),
                    ('move', 'Move'),
                    ('purchase', 'Purchase'),
                    ('resign', 'Resign'),
                    ('settlement', 'Settlement'),
                    ('timeout', 'Timeout'),
                ],
                max_length=32,
            ),
        ),
    ]
