# Generated by Django 5.2.1 on 2026-01-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('connect_five', '0008_alter_connectfivematch_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectfivestats',
            name='draws',
        ),
        migrations.AlterField(
            model_name='connectfivematch',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'Active'),
                    ('cancelled', 'Cancelled'),
                    ('finished_connect5', 'Finished (Connect 5)'),
                    ('finished_full_board', 'Finished (Full Board)'),
                    ('finished_resign', 'Finished (Resign)'),
                    ('finished_timeout', 'Finished (Timeout)'),
                ],
                default='active',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='connectfiveledgerentry',
            name='action',
            field=models.CharField(
                choices=[
                    ('challenge_refund', 'Challenge Refund'),
                    ('purchase', 'Purchase'),
                    ('stake_accept', 'Stake Accept'),
                    ('stake_lock', 'Stake Lock'),
                    ('win_payout', 'Win Payout'),
                ],
                max_length=32,
            ),
        ),
    ]
