# Generated by Django 5.2.1 on 2026-01-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('connect_five', '0009_remove_connectfivestats_draws_and_update_statuses'),
        ('users', '0005_useragreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectFiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                (
                    'match',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chat_messages',
                        to='connect_five.connectfivematch',
                    ),
                ),
                (
                    'sender',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='connect_five_chat_messages',
                        to='users.user',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_date'],
                'verbose_name': 'Connect Five chat message',
                'verbose_name_plural': 'Connect Five chat messages',
            },
        ),
        migrations.AddIndex(
            model_name='connectfivechatmessage',
            index=models.Index(fields=['match', 'created_date'], name='c5_chat_match_created_idx'),
        ),
    ]
