# Generated by Django 5.2.1 on 2026-02-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('connect_five', '0010_connectfivechatmessage'),
        ('users', '0005_useragreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectFiveEloSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('elo', models.PositiveIntegerField()),
                ('snapshot_date', models.DateField()),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='connect_five_elo_snapshots',
                        to='users.user',
                    ),
                ),
            ],
            options={
                'ordering': ['snapshot_date'],
                'verbose_name': 'Connect Five ELO snapshot',
                'verbose_name_plural': 'Connect Five ELO snapshots',
            },
        ),
        migrations.AddConstraint(
            model_name='connectfiveelosnapshot',
            constraint=models.UniqueConstraint(
                fields=('user', 'snapshot_date'), name='unique_connect_five_elo_snapshot'
            ),
        ),
        migrations.AddIndex(
            model_name='connectfiveelosnapshot',
            index=models.Index(fields=['user', 'snapshot_date'], name='c5_elo_snapshot_user_date_idx'),
        ),
    ]
