# Generated by Django 5.2.1 on 2025-06-25 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'description',
                    models.CharField(blank=True, help_text='Optional deployment description', max_length=255)
                ),
                (
                    'deployed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='frontend_deployments',
                        to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
            options={
                'verbose_name': 'Frontend Deployment',
                'verbose_name_plural': 'Frontend Deployments',
                'ordering': ['-deployed_at'],
            },
        ),
    ]
