# Generated by Django 5.2.1 on 2025-06-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontenddeployment',
            name='description',
        ),
    ]
