# Generated by Django 5.2.1 on 2025-06-25 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_description_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontenddeployment',
            options={
                'ordering': ['-created_date'],
                'verbose_name': 'Frontend Deployment',
                'verbose_name_plural': 'Frontend Deployments'
            },
        ),
        migrations.RemoveField(
            model_name='frontenddeployment',
            name='deployed_at',
        ),
    ]
