# Generated by Django 4.2.3 on 2023-11-14 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0001_initial'),
        ('social', '0003_alter_comment_owner_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='price_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='price_core',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cores.core'
            ),
        ),
    ]
