# Generated by Django 5.2.1 on 2025-05-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_price_amount_post_price_currency_post_recipient'),
    ]

    operations = [
        migrations.DeleteModel(name='PostReaction',),
    ]
