# Generated by Django 4.2.3 on 2024-04-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecture",
            name="duration_seconds",
        ),
    ]
