# Generated by Django 4.2.3 on 2024-04-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
