# Generated by Django 4.2.3 on 2025-05-24 20:09

from typing import List, Tuple

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: List[Tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name='AssetPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('filled_amount', models.PositiveBigIntegerField(default=0)),
                (
                    'fill_status',
                    models.CharField(
                        choices=[
                            ('OPEN', 'Open'),
                            ('PARTIALLY_FILLED', 'Partially Filled'),
                            ('FILLED', 'Filled'),
                            ('CANCELLED', 'Cancelled'),
                        ],
                        default='OPEN',
                        max_length=16,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fill_quantity', models.PositiveBigIntegerField()),
                ('trade_price', models.PositiveBigIntegerField()),
                ('overpayment_amount', models.PositiveBigIntegerField()),
                (
                    'buy_order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='buy_trades',
                        to='exchange.exchangeorder',
                    ),
                ),
                (
                    'sell_order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sell_trades',
                        to='exchange.exchangeorder',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
