# Generated by Django 4.2.3 on 2025-05-24 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cores', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeorder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='primary_currency',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='primary_orders', to='cores.core'
            ),
        ),
        migrations.AddField(
            model_name='exchangeorder',
            name='secondary_currency',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='secondary_orders', to='cores.core'
            ),
        ),
        migrations.AddField(
            model_name='assetpair',
            name='primary_currency',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='primary_asset_pairs', to='cores.core'
            ),
        ),
        migrations.AddField(
            model_name='assetpair',
            name='secondary_currency',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='secondary_asset_pairs', to='cores.core'
            ),
        ),
        migrations.AddConstraint(
            model_name='assetpair',
            constraint=models.UniqueConstraint(
                fields=('primary_currency', 'secondary_currency'), name='unique_asset_pair'
            ),
        ),
    ]
