# Generated by Django 5.2.1 on 2025-06-25 17:08

import uuid

from django.db import migrations, models
from django.db.models import Case, CharField, IntegerField, Value, When
from django.utils import timezone


def forwards(apps, schema_editor):
    apps.get_model('exchange', 'ExchangeOrder').objects.update(
        order_type=Case(
            When(order_type='BUY', then=Value(1)),
            When(order_type='SELL', then=Value(-1)),
            output_field=IntegerField(),
        ),
        fill_status=Case(
            When(fill_status='OPEN', then=Value(1)),
            When(fill_status='PARTIALLY_FILLED', then=Value(2)),
            When(fill_status='FILLED', then=Value(3)),
            When(fill_status='CANCELLED', then=Value(100)),
            output_field=IntegerField(),
        ),
    )


def backwards(apps, schema_editor):
    apps.get_model('exchange', 'ExchangeOrder').objects.update(
        order_type=Case(
            When(order_type=1, then=Value('BUY')),
            When(order_type=-1, then=Value('SELL')),
            output_field=CharField(),
        ),
        fill_status=Case(
            When(fill_status=1, then=Value('OPEN')),
            When(fill_status=2, then=Value('PARTIALLY_FILLED')),
            When(fill_status=3, then=Value('FILLED')),
            When(fill_status=100, then=Value('CANCELLED')),
            output_field=CharField(),
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ('exchange', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.RenameField(model_name='exchangeorder', old_name='filled_amount', new_name='filled_quantity'),
        migrations.RenameField(model_name='exchangeorder', old_name='fill_status', new_name='status'),
        migrations.RenameField(model_name='trade', old_name='fill_quantity', new_name='filled_quantity'),
        migrations.RenameField(model_name='trade', old_name='trade_price', new_name='price'),
        migrations.RenameField(model_name='exchangeorder', old_name='order_type', new_name='side'),
        migrations.AlterField(
            model_name='exchangeorder',
            name='side',
            field=models.SmallIntegerField(choices=[(1, 'Buy'), (-1, 'Sell')]),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Open'), (2, 'Partially Filled'), (3, 'Filled'), (100, 'Cancelled')], default=1
            ),
        ),
        migrations.AlterField(
            model_name='exchangeorder', name='created_date', field=models.DateTimeField(default=timezone.now)
        ),
        migrations.AlterField(
            model_name='exchangeorder', name='modified_date', field=models.DateTimeField(default=timezone.now)
        ),
        migrations.AlterField(
            model_name='trade', name='created_date', field=models.DateTimeField(default=timezone.now)
        ),
        migrations.AlterField(
            model_name='trade', name='modified_date', field=models.DateTimeField(default=timezone.now)
        ),
        migrations.CreateModel(
            name='OrderProcessingLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acquired_at', models.DateTimeField(null=True, blank=True)),
                ('trade_at', models.DateTimeField(null=True, blank=True)),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.Value(1), name='only_one_row_allowed')],
            },
        ),
    ]
