# Generated by Django 5.2.1 on 2025-07-28 11:14

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('currencies', '0008_whitepaper'),
        ('exchange', '0003_remove_exchangeorder_order_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveBigIntegerField()),
                ('change_1h', models.FloatField()),
                ('change_24h', models.FloatField()),
                ('change_7d', models.FloatField()),
                ('volume_24h', models.PositiveBigIntegerField()),
                ('market_cap', models.PositiveBigIntegerField()),
                (
                    'sparkline',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveBigIntegerField(blank=True, null=True),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    'primary_currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='primary_trade_history_items',
                        to='currencies.currency',
                    ),
                ),
                (
                    'secondary_currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='secondary_trade_history_items',
                        to='currencies.currency',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('primary_currency', 'secondary_currency'), name='unique_trade_history_item'
                    )
                ],
            },
        ),
    ]
