# Generated by Django 5.2.1 on 2025-08-02 06:52

from django.conf import settings
from django.db import migrations, models


def populate_exchange_order_asset_pair(apps, schema_editor):
    ExchangeOrder = apps.get_model('exchange', 'ExchangeOrder')
    AssetPair = apps.get_model('exchange', 'AssetPair')
    asset_pairs = {(asset_pair.primary_currency_id, asset_pair.secondary_currency_id): asset_pair
                   for asset_pair in AssetPair.objects.all()}
    for order in ExchangeOrder.objects.all().iterator():
        order.asset_pair = asset_pairs[(order.primary_currency_id, order.secondary_currency_id)]
        order.save()


def reverse_exchange_order_asset_pair(apps, schema_editor):
    ExchangeOrder = apps.get_model('exchange', 'ExchangeOrder')
    for order in ExchangeOrder.objects.all().iterator():
        order.primary_currency_id = order.asset_pair.primary_currency_id
        order.secondary_currency_id = order.asset_pair.secondary_currency_id
        order.save()


def populate_trade_history_item_asset_pair(apps, schema_editor):
    TradeHistoryItem = apps.get_model('exchange', 'TradeHistoryItem')
    AssetPair = apps.get_model('exchange', 'AssetPair')
    asset_pairs = {(asset_pair.primary_currency_id, asset_pair.secondary_currency_id): asset_pair
                   for asset_pair in AssetPair.objects.all()}
    for item in TradeHistoryItem.objects.all().iterator():
        item.asset_pair = asset_pairs[(item.primary_currency_id, item.secondary_currency_id)]
        item.save()


def reverse_trade_history_item_asset_pair(apps, schema_editor):
    TradeHistoryItem = apps.get_model('exchange', 'TradeHistoryItem')
    for item in TradeHistoryItem.objects.all().iterator():
        item.primary_currency_id = item.asset_pair.primary_currency_id
        item.secondary_currency_id = item.asset_pair.secondary_currency_id
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_tradehistoryitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeorder',
            name='asset_pair',
            field=models.ForeignKey(
                null=True,
                on_delete=models.PROTECT,
                related_name='exchange_orders',
                to='exchange.assetpair',
            ),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='primary_currency',
            field=models.ForeignKey(
                null=True, on_delete=models.CASCADE, related_name='primary_orders', to='currencies.currency'
            ),
        ),
        migrations.AlterField(
            model_name='exchangeorder',
            name='secondary_currency',
            field=models.ForeignKey(
                null=True, on_delete=models.CASCADE, related_name='secondary_orders', to='currencies.currency'
            ),
        ),
        migrations.RunPython(populate_exchange_order_asset_pair, reverse_code=reverse_exchange_order_asset_pair),
        migrations.RemoveField(model_name='exchangeorder', name='primary_currency'),
        migrations.RemoveField(model_name='exchangeorder', name='secondary_currency'),
        migrations.AddField(
            model_name='tradehistoryitem',
            name='asset_pair',
            field=models.OneToOneField(
                null=True,
                on_delete=models.CASCADE,
                related_name='trade_history_items',
                to='exchange.assetpair',
                unique=True
            ),
        ),
        migrations.AlterField(
            model_name='tradehistoryitem',
            name='primary_currency',
            field=models.ForeignKey(
                null=True,
                on_delete=models.CASCADE,
                related_name='primary_trade_history_items',
                to='currencies.currency'
            ),
        ),
        migrations.AlterField(
            model_name='tradehistoryitem',
            name='secondary_currency',
            field=models.ForeignKey(
                null=True,
                on_delete=models.CASCADE,
                related_name='secondary_trade_history_items',
                to='currencies.currency'
            ),
        ),
        migrations.RunPython(
            populate_trade_history_item_asset_pair, reverse_code=reverse_trade_history_item_asset_pair
        ),
        migrations.RemoveConstraint(model_name='tradehistoryitem', name='unique_trade_history_item'),
        migrations.RemoveField(model_name='tradehistoryitem', name='primary_currency'),
        migrations.RemoveField(model_name='tradehistoryitem', name='secondary_currency'),
        migrations.AlterField(
            model_name='exchangeorder',
            name='owner',
            field=models.ForeignKey(on_delete=models.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
