# Generated by Django 4.2.3 on 2024-05-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manual_contribution_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='manual_contribution_reward_daily_limit',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
