# Generated by Django 5.2.1 on 2025-06-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_discord_username_user_facebook_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='twitter_username',
            new_name='x_username',
        ),
    ]
