# Generated by Django 4.2.3 on 2024-08-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_manual_contribution_allowed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discord_username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
