# Generated by Django 4.2.3 on 2024-08-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_manual_contribution_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_user_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_username',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
