# Generated by Django 4.2.3 on 2025-05-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_discord_user_id_user_discord_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discord_user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='discord_username',
        ),
    ]
