# Generated by Django 5.2.1 on 2025-07-19 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('terms_agreed_at', models.DateTimeField()),
                ('privacy_policy_agreed_at', models.DateTimeField()),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='agreement',
                        to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
            options={
                'db_table': 'users_useragreement',
            },
        ),
    ]
