# Generated by Django 4.2.3 on 2025-05-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_discord_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_manual_contribution_allowed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='manual_contribution_reward_daily_limit',
        ),
    ]
