# Generated by Django 5.2.1 on 2025-08-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_useragreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={
                'indexes': [
                    models.Index(models.functions.Lower('username'), fields=[], name='users_user_username_idx')
                ],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(models.functions.Lower('username'), fields=[], name='users_user_username_idx'),
        ),
    ]
