BOARD_SIZE = 15
CHAT_MESSAGE_MAX_LENGTH = 280
CHAT_MESSAGE_PAGE_SIZE = 50
CONNECT_LENGTH = 5
ELO_K_PROVISIONAL = 40
ELO_K_STANDARD = 32
ELO_MINIMUM = 100
ELO_PROVISIONAL_MATCHES = 10
ELO_STARTING_SCORE = 1500
TIME_LIMIT_CHOICES = (300, 600, 900, 1800)

SPECIAL_PRICES = {
    'H2': 4,
    'V2': 4,
    'BOMB': 3,
}


def create_empty_board():
    return [[0 for _ in range(BOARD_SIZE)] for _ in range(BOARD_SIZE)]
