# Generated by Django 4.2.2 on 2023-06-21 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cores', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'primary_currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='primary_asset_pairs',
                        to='cores.core'
                    )
                ),
                (
                    'secondary_currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='secondary_asset_pairs',
                        to='cores.core'
                    )
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='assetpair',
            constraint=models.UniqueConstraint(
                fields=('primary_currency', 'secondary_currency'), name='unique_asset_pair'
            ),
        ),
    ]
