# Generated by Django 4.2.2 on 2023-06-21 20:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cores', '0002_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('filled_amount', models.PositiveBigIntegerField(default=0)),
                (
                    'fill_status',
                    models.CharField(
                        choices=[('OPEN', 'Open'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Filled'),
                                 ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')],
                        default='OPEN',
                        max_length=16
                    )
                ),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    'primary_currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='primary_orders', to='cores.core'
                    )
                ),
                (
                    'secondary_currency',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='secondary_orders', to='cores.core'
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
