# Generated by Django 4.2.2 on 2023-06-24 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fill_quantity', models.PositiveBigIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                (
                    'buy_order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='buy_trades', to='orders.order'
                    )
                ),
                (
                    'sell_order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='orders.order'
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
