# Generated by Django 4.2.2 on 2023-06-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_trade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='price',
            new_name='trade_price',
        ),
        migrations.AddField(
            model_name='trade',
            name='overpayment_amount',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
