# Generated by Django 4.2.2 on 2023-06-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_price_trade_trade_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fill_status',
            field=models.CharField(
                choices=[('OPEN', 'Open'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Filled'),
                         ('CANCELLED', 'Cancelled')],
                default='OPEN',
                max_length=16
            ),
        ),
    ]
