# Generated by Django 4.2.2 on 2023-07-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='user',
            new_name='owner',
        ),
    ]
