# Generated by Django 5.2.1 on 2025-05-23 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='images/')),
                ('ticker', models.CharField(max_length=5, unique=True)),
                (
                    'currency_type',
                    models.CharField(
                        choices=[('internal', 'Internal'), ('external', 'External')],
                        default='internal',
                        max_length=255
                    )
                ),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
