# Generated by Django 5.2.1 on 2025-05-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
    ]
