# Generated by Django 5.2.1 on 2025-05-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currency_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=255),
        ),
        migrations.AlterField(
            model_name='currency',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
