# Generated by Django 5.2.1 on 2025-05-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('currencies', '0003_alter_currency_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
