# Generated by Django 5.2.1 on 2025-06-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('currencies', '0005_alter_currency_domain_mint'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
