# Generated by Django 5.2.1 on 2025-06-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0007_currency_discord_username_currency_facebook_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='twitter_username',
            new_name='x_username',
        ),
    ]
