# Generated by Django 4.2.2 on 2023-06-29 00:48

from typing import List, Tuple

from django.db import migrations, models

import thenewboston.general.validators


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                (
                    'sender',
                    models.CharField(
                        max_length=64, validators=[thenewboston.general.validators.HexStringValidator(64)]
                    )
                ),
                (
                    'signature',
                    models.CharField(
                        max_length=128, validators=[thenewboston.general.validators.HexStringValidator(128)]
                    )
                ),
                (
                    'recipient',
                    models.CharField(
                        max_length=64, validators=[thenewboston.general.validators.HexStringValidator(64)]
                    )
                ),
                ('amount', models.PositiveBigIntegerField()),
                ('transaction_fee', models.PositiveBigIntegerField()),
                ('payload', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
