# TODO(dmu) LOW: Move some of these to thenewboston/project/settings/custom.py
ACCOUNT_NUMBER_LENGTH = 64
DEFAULT_INVITATION_LIMIT = 10
DEFAULT_PAGE_SIZE = 20
MAX_MINT_AMOUNT = 1_000_000_000
SIGNATURE_LENGTH = 128
SIGNING_KEY_LENGTH = 64
TRANSACTION_FEE = 1
