# TODO(dmu) LOW: Move some of these to thenewboston/project/settings/custom.py
ACCOUNT_NUMBER_LENGTH = 64
DEFAULT_INVITATION_LIMIT = 10
DEFAULT_PAGE_SIZE = 20
OPENAI_IMAGE_CREATION_FEE = 1
SIGNATURE_LENGTH = 128
SIGNING_KEY_LENGTH = 64
TRANSACTION_FEE = 1
