# Generated by Django 4.2.3 on 2025-05-24 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import thenewboston.general.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                (
                    'sender',
                    models.CharField(
                        max_length=64, validators=[thenewboston.general.validators.HexStringValidator(64)]
                    )
                ),
                (
                    'signature',
                    models.CharField(
                        max_length=128, validators=[thenewboston.general.validators.HexStringValidator(128)]
                    )
                ),
                (
                    'recipient',
                    models.CharField(
                        max_length=64, validators=[thenewboston.general.validators.HexStringValidator(64)]
                    )
                ),
                ('amount', models.PositiveBigIntegerField()),
                ('transaction_fee', models.PositiveBigIntegerField()),
                ('payload', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('balance', models.PositiveBigIntegerField(default=0)),
                (
                    'deposit_account_number',
                    models.CharField(
                        max_length=64, validators=[thenewboston.general.validators.HexStringValidator(64)]
                    )
                ),
                ('deposit_balance', models.PositiveBigIntegerField(default=0)),
                (
                    'deposit_signing_key',
                    models.CharField(
                        max_length=64, validators=[thenewboston.general.validators.HexStringValidator(64)]
                    )
                ),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cores.core')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wire',
            fields=[
                (
                    'block_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='wallets.block'
                    )
                ),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                (
                    'wire_type',
                    models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw')], max_length=8)
                ),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cores.core')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('wallets.block',),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('owner', 'core'), name='unique_owner_core'),
        ),
    ]
