# Generated by Django 4.2.2 on 2023-06-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'core'), name='unique_user_core'),
        ),
    ]
