# Generated by Django 4.2.2 on 2023-06-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_wallet_unique_user_core'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='unique_user_core',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('owner', 'core'), name='unique_owner_core'),
        ),
    ]
