# Generated by Django 4.2.3 on 2024-01-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubuser',
            options={
                'verbose_name': 'GitHub User',
                'verbose_name_plural': 'GitHub Users'
            },
        ),
    ]
