# Generated by Django 4.2.3 on 2024-03-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_alter_githubuser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pull',
            old_name='issue_id',
            new_name='issue_number',
        ),
        migrations.AddConstraint(
            model_name='pull',
            constraint=models.UniqueConstraint(fields=('issue_number', 'repo'), name='unique_pull_issue_number_repo'),
        ),
        migrations.AlterField(
            model_name='pull',
            name='issue_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='pull',
            name='github_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='github.githubuser'),
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issue_id',
            new_name='issue_number',
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('issue_number', 'repo'), name='unique_issue_issue_number_repo'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='repo',
            name='owner_name',
            field=models.CharField(default='thenewboston-developers', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repo',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='repo',
            constraint=models.UniqueConstraint(fields=('owner_name', 'name'), name='unique_repo_owner_name_name'),
        ),
        migrations.AlterField(
            model_name='pull',
            name='repo',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='pulls', to='github.repo'),
        ),
    ]
