# Generated by Django 4.2.3 on 2024-04-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_pull_added_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='contribution_branch',
            field=models.CharField(default='main', max_length=100),
        ),
    ]
