# Generated by Django 4.2.3 on 2024-05-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_repo_contribution_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pull',
            name='assessment_explanation',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pull',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
