# Generated by Django 4.2.2 on 2023-07-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(default='zChXUK', max_length=6, unique=True),
        ),
    ]
