# Generated by Django 4.2.3 on 2023-07-30 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_remove_invitation_user_invitation_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
