# Generated by Django 4.2.2 on 2023-07-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_alter_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
