# Generated by Django 4.2.2 on 2023-07-12 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cores', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                (
                    'activation_status',
                    models.CharField(
                        choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft')], default='DRAFT', max_length=6
                    )
                ),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=200)),
                ('price_amount', models.PositiveBigIntegerField()),
                ('price_core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cores.core')),
                (
                    'seller',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
