# Generated by Django 4.2.2 on 2023-07-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartproduct'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartproduct',
            constraint=models.UniqueConstraint(fields=('buyer', 'product'), name='unique_cart_product'),
        ),
    ]
