# Generated by Django 4.2.2 on 2023-07-13 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0002_initial'),
        ('shop', '0005_order_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price_amount',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price_core',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cores.core'),
            preserve_default=False,
        ),
    ]
