# Generated by Django 4.2.2 on 2023-07-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderproduct_quantity_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
