# Generated by Django 4.2.3 on 2024-03-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_artworktransfer_price_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image_url',
            field=models.URLField(
                help_text='URL of an OpenAI-generated image', max_length=1024, null=True, unique=True
            ),
        ),
    ]
